server:
  port: 8090
eureka:
  instance:
    prefer-ip-address: true
    hostname:  ${spring.application.name}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST_NAME:localhost}:8761/eureka
  
      
      
spring:
  application:
    name: gateway-server
  cloud:  
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/ecommerce
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true 
  info:
    env:
      enabled: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://otel-collector:4317
      protocol: grpc
    metrics:
      export:
        enabled: false
  metrics:
    tags:
      application: ${spring.application.name}
logging:
  level:
    root: info
    com:
      mayuktha:
        gateway: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

