spring:
  application:
    name: eureka-server
server:
  port: 8761
eureka:
  instance:
    hostname: ${EUREKA_HOST_NAME:localhost}
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
management:
  endpoints:
    web:
      exposure:
        include:
        - prometheus
  endpoint:
    prometheus:
      enabled: true
  
  prometheus:
    metrics:
      export:
        enabled: true