apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_USER
              value: mahesh         # Custom user (optional)
            - name: MYSQL_PASSWORD
              value: mahesh # Password for custom user (optional)
            - name: MYSQL_DATABASE
              value: ecommerce
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-storage
      volumes:
        - name: mysql-storage
          hostPath:
            path: /host_mnt/c/Mahesh/Spring-POC/kubernates-full-setup/mysqldata  # IMPORTANT: Linux-style path to Windows dir - So C:\k8s-data\mysql → /host_mnt/c/k8s-data/mysql
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
  type: NodePort
