apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
data:
  loki.yaml: |
    auth_enabled: false
    
    server:
      http_listen_port: 3100
      grpc_listen_port: 9095
    
    common:
      path_prefix: /loki
      storage:
        filesystem:
          chunks_directory: /loki/chunks
          rules_directory: /loki/rules
      replication_factor: 1
    
    schema_config:
      configs:
        - from: "2020-10-24"
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h
    
    storage_config:
      boltdb_shipper:
        active_index_directory: /loki/boltdb-shipper-active
        cache_location: /loki/boltdb-shipper-cache
        shared_store: filesystem
      filesystem:
        directory: /loki/chunks
    
    ingester:
      wal:
        dir: /loki/wal
      lifecycler:
        ring:
          kvstore:
            store: inmemory
    
    compactor:
      working_directory: /loki/compactor
      shared_store: filesystem
    
    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      
      
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      initContainers:
      - name: init-storage
        image: busybox:1.35
        command:
        - sh
        - -c
        - |
          mkdir -p /loki/{chunks,rules,wal,boltdb-shipper-active,boltdb-shipper-cache,compactor}
          chown -R 10001:10001 /loki
        volumeMounts:
        - name: storage
          mountPath: /loki
      securityContext:
        fsGroup: 10001
      containers:
      - name: loki
        image: grafana/loki:2.9.4
        securityContext:
          runAsUser: 10001
          runAsGroup: 10001
        args:
        - -config.file=/etc/loki/loki.yaml
        ports:
        - containerPort: 3100
          name: http
        - containerPort: 9095
          name: grpc
        volumeMounts:
        - name: config
          mountPath: /etc/loki
        - name: storage
          mountPath: /loki
      volumes:
      - name: config
        configMap:
          name: loki-config
      - name: storage
        hostPath:
          path: /tmp/loki-data
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: loki
spec:
  ports:
  - port: 3100
    targetPort: 3100
  selector:
    app: loki          