server:
  port: 8081
spring:
  application:
    name: products
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/ecommerce
    username: root
    password: root
  cloud:
    aws:
      credentials:
        access-key: AKIAVY2PHCGUJF7BDZLW
        secret-key: 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
      region:
        static: ap-south-1
      s3:
        enabled: true
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://${EUREKA_HOST_NAME:localhost}:8070/eureka
logging:
  file:
    name: product.log