server:
  port: 8080
spring:
  application:
    name: user-mgmt
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/ecommerce
    username: root
    password: root
#  autoconfigure:
#    exclude:
#    - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
logging:
  level:
    com.mayuktha.usersmgmt.*: DEBUG
  file:
    name: user-mgmt.log
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://${EUREKA_HOST_NAME:localhost}:8070/eureka