server:
  port: 8082
spring:
  application:
    name: orders
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/ecommerce
    username: root
    password: root
logging:
  level:
    com.mayuktha.orders.*: DEBUG
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://${EUREKA_HOST_NAME:localhost}:8070/eureka